name: Build Chain

on: [push, pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Build Chain Flow
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@v3
        with:
          definition-file: https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/master/.build-chain-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
